### ISSUE TITLE
Issue with 1.0.5 install

### ISSUE THREAD

**Issue by miked1959blue** [bostrowski/Pretius-APEX-Enhanced-Lov-Item#24]
Hi , I finally got round to installing 1.0.5, I cloned my Apex app, installed the packages in the database and then installed the plugin. However, when I now try to run my Apex 19 app, I get the following error when displayed a page containing an Enhanced LOV item. I tried creating a new pag e with only one item on it and got the same error, see below:

HTML1300: Navigation occurred.
f (1,1)

HTML1512: Unmatched end tag.
f (203,237)

# (P964_INTEREST_TYPE_ID) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _create options [object Object] [object Object]

# (P964_INTEREST_TYPE_ID) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _maskCreateNew element [object HTMLInputElement]

# (P964_INTEREST_TYPE_ID) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _createItemPopupButton

# (P964_INTEREST_TYPE_ID) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _createItemAjaxButton

# (P964_INTEREST_TYPE_ID) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _maskCreateNew classes text_field,apex-item-text

jQuery.Deferred exception: Object doesn't support property or method 'size' TypeError: Object doesn't support property or method 'size'
   at _create (https://demo-mpowerus.mpower-cloud.com/ords_demous/demous/r/110/files/plugin/585361118198220467/v117/enhancedLovItem.js:147:5)
   at Anonymous function (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:6803)
   at a.Widget.prototype._createWidget (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:8449)
   at a[i][b] (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:6360)
   at Anonymous function (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:8203)
   at each (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:2563)
   at w.prototype.each (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified

SCRIPT438: SCRIPT438: Object doesn't support property or method 'size'
desktop_all.min.js (2,31040)

2HTML1300: Navigation occurred.
f (1,1)

# (P8_DESCRIPTION) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _create options [object Object] [object Object]

# (P8_DESCRIPTION) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _maskCreateNew element [object HTMLInputElement]

# (P8_DESCRIPTION) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _createItemPopupButton

# (P8_DESCRIPTION) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _createItemAjaxButton

# (P8_DESCRIPTION) PL.OSTROWSKIBARTOSZ.APEX.ENHANCEDLOVITEM: _maskCreateNew classes text_field,apex-item-text

jQuery.Deferred exception: Object doesn't support property or method 'size' TypeError: Object doesn't support property or method 'size'
   at _create (https://demo-mpowerus.mpower-cloud.com/ords_demous/demous/r/110/files/plugin/585361118198220467/v117/enhancedLovItem.js:147:5)
   at Anonymous function (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:6803)
   at a.Widget.prototype._createWidget (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:8449)
   at a[i][b] (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:6360)
   at Anonymous function (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:27:8203)
   at each (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified/desktop_all.min.js?v=19.1.0.00.15:2:2563)
   at w.prototype.each (https://demo-mpowerus.mpower-cloud.com/i/libraries/apex/minified

HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
GET - https://demo-mpowerus.mpower-cloud.com/widgets/size_grip.png

SCRIPT438: SCRIPT438: Object doesn't support property or method 'size'

Any ideas as to what I have done wrong?

Really looking forward to hearing back.

Yours,

**Comment by miked1959blue** [comment]
> Object doesn't support property or method 'size'

Hi, I managed to overcome the error by setting the Include jQuery Migrate to Yes on the UI control panel. Does that imply that there are some dependencies on earlier version of jQuery?

**Comment by bostrowski** [comment]
@miked1959blue 
this week version 1.1.0 will be released. 

Regarding your issue: it occurred that in version 1.0.5 I've skipped 1 line (# 147) where method size remained.

Using jQuery Migrate shouldn't be the solution. 

You can replace this line #147 in file enhancedLovItem.js 
```js
this.inlineDialog = this.element.closest('.t-DialogRegion').size() > 0;
```
with
```js
this.inlineDialog = this.element.closest('.t-DialogRegion').length > 0;
```
or wait for new release to be released.
